init workflow
NStegura/gophermart pull request #1
Opened 2024-01-14 20:01 UTC by NStegura

2024-02-05 13:38 UTC, s-shpak requested changes

2024-02-05 13:38 UTC, s-shpak commented on DockerfileAccrual
Докерфайлы лучше называть в формате "accrual.dockerfile", чтобы IDE распознавали синтаксис

2024-02-05 13:38 UTC, s-shpak commented on cmd/gophermart/main.go
> +	if err = db.RunMigrations(); err != nil {
Было бы лучше, если бы это вызывалось при инициализации хендлера к БД, а не напрямую в слое логики приложения

2024-02-05 13:38 UTC, s-shpak commented on internal/app/gophermartapi/config.go
> +	defaultSecretKey   = "gljfsj;312sf;kdhrf;" // ?????? very bad
Я бы не ставил никакой дефолтный ключ и проверял бы при старте сервиса, что ключ передан сервису. Сейчас отсутствие дефолтного ключа крашит автотесты ?

2024-02-05 13:38 UTC, s-shpak commented on internal/app/gophermartapi/config.go
> +	defaultDatabaseURI = ""
```suggestion
	defaultDatabaseDSN = ""
```

2024-02-05 13:38 UTC, s-shpak commented on internal/app/gophermartapi/middleware_auth.go
> +type CtxUserID struct{}
Ключи для храения данных внутри контекста лучше определять так: https://medium.com/@matryer/context-keys-in-go-5312346a868d

2024-02-05 13:38 UTC, s-shpak commented on internal/app/gophermartapi/server.go
> +	r.Get("/panic", func(w http.ResponseWriter, r *http.Request) {
Такое надо убирать из релизных версий

2024-02-05 13:38 UTC, s-shpak commented on internal/clients/accrual/client.go
> +type RequestError struct {
Этот тип где-нибудь используется ?

2024-02-05 13:38 UTC, s-shpak commented on internal/clients/accrual/client.go
> +	ok := c.semaphore.TryAcquire(1)
А зачем ограничивать запросы здесь ? По идее, нам ничего не запрещает делать параллельные запросы к `accrual`

2024-02-05 13:38 UTC, s-shpak commented on internal/clients/accrual/client.go
> +			if err = c.semaphore.Acquire(ctx, 1); err != nil {
Сделай лучше не через семафор: пусть диспетчер передает сигнал воркером о том, что надо подождать столько-то секунд до продолжения обработки

2024-02-05 13:38 UTC, s-shpak commented on internal/repo/migrations/00001_create_user.sql
> +    login       TEXT UNIQUE,
Может ли это поле быть `NULL` ? Кроме того все поля лучше помечать как `NULL/NOT NULL`

2024-02-05 13:38 UTC, s-shpak commented on internal/services/auth/auth.go
> +func (s *Service) GenerateUserSalt(complexity int64) string {
Для добавления соли можно использовать пакет `bcrypt`, он делает это автоматически

2024-02-06 15:58 UTC, NStegura commented on cmd/gophermart/main.go
> +	if err = db.RunMigrations(); err != nil {
немного не понял, обсудим на созвоне

2024-02-06 15:59 UTC, NStegura commented on internal/app/gophermartapi/config.go
> +	defaultSecretKey   = "gljfsj;312sf;kdhrf;" // ?????? very bad
Вроде да, поэтому я его выставил здесь, тк автотесты не прокидывают в энвах

2024-02-06 16:31 UTC, NStegura commented on internal/app/gophermartapi/middleware_auth.go
> +type CtxUserID struct{}
А есть разница?
Я тут сделал через getUserID() + он используется только в этом пакете.
Знаю только, что коллизии могут появиться, если использовать string обычный, но особо не нашел разницы между именованным типом от сроки и структурой

2024-02-06 16:33 UTC, NStegura commented on internal/app/gophermartapi/middleware_auth.go
> +type CtxUserID struct{}
Пока поправил на некэкспортируемый

2024-02-06 16:37 UTC, NStegura commented on internal/clients/accrual/client.go
> +type RequestError struct {
Нет, хотел сначала заиспользовать и забыл убрать
Убрал

2024-02-06 16:41 UTC, NStegura commented on internal/clients/accrual/client.go
> +	ok := c.semaphore.TryAcquire(1)
Это лучше обсудить на созвоне, у меня были вопросы пока я это делал
Тут хитрость, что идет проверка занят он или нет, параллельные даст сделать, тк он сразу его отпускает

	ok := c.semaphore.TryAcquire(1)
	if !ok {
		return orderAccrual, ErrClientSemaphore
	} else {
		c.semaphore.Release(1)
	}
Но если нам пришло http.StatusTooManyRequests, то мы заблочим клиент на время

Мне нравится идея хранить эту логичу в клиенте, его могут использовать не только из сервиса джоб, а сервис джоб не должен знать по идее, что там с клиентом и рулить логикой отправки, а только отправлять по возможности (отправил и забыл или встал в ожидание)

2024-02-06 17:07 UTC, NStegura commented on internal/services/auth/auth.go
> +func (s *Service) GenerateUserSalt(complexity int64) string {
Те хранить не рандомную соль для каждого пользака, а хеш от пароля с помощью bcrypt?
Спрошу на созвоне

2024-02-09 11:51 UTC, NStegura commented on internal/clients/accrual/client.go
> +	ok := c.semaphore.TryAcquire(1)
перепишу на atomic

2024-02-11 14:59 UTC, NStegura commented on internal/clients/accrual/client.go
> +			if err = c.semaphore.Acquire(ctx, 1); err != nil {
переписал на atomic

2024-02-20 13:57 UTC, s-shpak approved these changes

2024-02-28 13:11 UTC, merged